# Generated by Django 2.2.6 on 2020-09-09 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0007_auto_20200909_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion', models.NullBooleanField(default=None, verbose_name='Чтение завершено')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookreading_book', to='p_library.Book', verbose_name='Книга')),
            ],
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Имя')),
                ('books', models.ManyToManyField(through='p_library.BookReading', to='p_library.Book', verbose_name='Книги')),
            ],
        ),
        migrations.AddField(
            model_name='bookreading',
            name='reader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookreading_reader', to='p_library.Reader', verbose_name='Читатель'),
        ),
    ]
