# Generated by Django 3.1.1 on 2020-09-11 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0009_auto_20200910_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='completion',
            field=models.BooleanField(default=None, null=True, verbose_name='Чтение завершено'),
        ),
        migrations.AlterField(
            model_name='book',
            name='reader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reader_books', to='p_library.reader', verbose_name='Читатель'),
        ),
    ]
