# Generated by Django 3.1.1 on 2020-09-11 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0010_auto_20200911_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='static'),
        ),
    ]
